version: "3"
services:
  app:
    image: node:alpine
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: npm run start
    depends_on:
      - jupyter
    links:
      - jupyter
  jupyter:
    build: ./jupyter
    ports:
      - 8888:8888

